import prototype3_pickled as s


beatles = "Love, love, love Love, love, love Love, love, love There's nothing you can do that can't be done Nothing you can sing that can't be sung Nothing you can say, but you can learn how to play the game It's easy Nothing you can make that can't be made No one you can save that can't be saved Nothing you can do, but you can learn how to be you in time It's easy All you need is love, all you need is love All you need is love, love, love is all you need All you need is love All you need is love, love, love is all you need There's nothing you can know that isn't known Nothing you can see that isn't shown There's nowhere you can be that isn't where you're meant to be It's easy All you need is love, all you need is love All you need is love, love, love is all you need All you need is love (All together now) All you need is love (Everybody) All you need is love, love, love is all you need Love is all you need Love is all you need Love is all you need Love is all you need Love is all you need Love is all you need Love is all you need Love is all you need Love is all you need Love is all you need Love is all you need Yesterday Oh yeah (She love you, yeah, yeah, yeah) (She love you, yeah, yeah, yeah)"

evanescence = "I'm so tired of being here Suppressed by all my childish fears And if you have to leave I wish that you would just leave 'Cause your presence still lingers here And it won't leave me alone These wounds won't seem to heal, this pain is just too real There's just too much that time cannot erase When you cried, I'd wipe away all of your tears When you'd scream, I'd fight away all of your fears And I held your hand through all of these years But you still have all of me You used to captivate me by your resonating light Now, I'm bound by the life you left behind Your face it haunts my once pleasant dreams Your voice it chased away all the sanity in me These wounds won't seem to heal, this pain is just too real There's just too much that time cannot erase When you cried, I'd wipe away all of your tears When you'd scream, I'd fight away all of your fears And I held your hand through all of these years But you still have all of me I've tried so hard to tell myself that you're gone But though you're still with me, I've been alone all along When you cried, I'd wipe away all of your tears When you'd scream, I'd fight away all of your fears And I held your hand through all of these years You still have all of me, me, me"

cant = "Loveliest of trees, the cherry now Is hung with bloom along the bough, And stands about the woodland ride Wearing white for Eastertide. Now, of my threescore years and ten, Twenty will not come again, And take from seventy springs a score, It only leaves me fifty more. And since to look at things in bloom Fifty springs are little room, About the woodlands I will go To see the cherry hung with snow."

imagine = "Imagine there's no heaven It's easy if you try No hell below us Above us only sky Imagine all the people living for today Imagine there's no countries It isn't hard to do Nothing to kill or die for And no religion too Imagine all the people living life in peace, you You may say I'm a dreamer But I'm not the only one I hope some day you'll join us And the world will be as one Imagine no possessions I wonder if you can No need for greed or hunger A brotherhood of man Imagine all the people sharing all the world, you You may say I'm a dreamer But I'm not the only one I hope some day you'll join us And the world will be as one"

dontletmedown = "Don't let me down, don't let me down Don't let me down, don't let me down Nobody ever loved me like she does Oh, she does, yeah, she does And if somebody loved me like she do me Oh, she do me, yes, she does Don't let me down, don't let me down Don't let me down, don't let me down I'm in love for the first time Don't you know it's gonna last It's a love that lasts forever It's a love that had no past Don't let me down, don't let me down Don't let me down, don't let me down And from the first time that she really done me Oh, she done me, she done me good I guess nobody ever really done me Oh, she done me, she done me good Don't let me down, hey, don't let me down Heee! Don't let me down Don't let me down Don't let me down, don't let me let down Can you dig it? Don't let me down"

print(s.sentiment(beatles)[1])
print(s.sentiment(evanescence))
print(s.sentiment(cant))
print(s.sentiment(imagine))
print(s.sentiment(dontletmedown))

